### ISSUE TITLE
[1.12.2] Possible Memory Leak when the Armor from Rats renders.

### ISSUE THREAD

**Issue by Z-Tunic** [Rebirth-of-the-Night/Rats-RatN-Edition#1]
In a modded survival world that has Rats: RatN-Edition installed... I got a Pirat Hat and gave it  to one of my tamed rats to wear since... well... arrr, pirate rat. Now... I didn't think anything of it but overtime I noticed something was off.

If the Armor from Rats renders whether it be on the inventory screen, in your eyesight view or if using an addon to show a preview of the mob such as ToroHUD... the Memory usage gradually goes up overtime. Not sure if it'll crash or something but my PC did warn me of having low ram even though I have 32GB of it installed. (I have 12GB allocated as it has 300+ mods installed.)

Now... in this instance for testing... the only mods installed are...

Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
jei_1.12.2-4.16.1.302
llibrary-1.7.19-1.12.2
rats-3.2.19-1.12.2

Here's an image of my memory usage in task manager. I am aware that it goes up overtime but it stops rising if I remain still in one spot and don't move or anything... this is what I have...

![](https://cdn.discordapp.com/attachments/377171551155650560/870753312876691567/memoryusagerising.PNG)
Left: I am wearing almost full diamond armor and my memory usage is about 6.2GB or so. It seems to have stopped around there so that's when I took the screen cap for it.

Right: I put on the Pirat Hat and left the PC on for maybe an hour and... my usage has gone up to 8.3GB and still climbing. It'll keep going up until you remove the Pirat Hat... as in... it doesn't render on your screen.

=====

Doing some looking around, apparently this was happening in the original mod as well, something about it rendering the armor every tick. I found out about this from the issue here.

https://github.com/Electroblob77/Wizardry/issues/648

It might be all the armors in this case, since in the issue the Chef's Hat was mentioned and I got it with the Pirat Hat.

**Comment by Davoleo** [comment]
yeah, I've archived the faulty version and uploaded a new working version, thanks for the prompty answers

**Comment by owenthewizard** [comment]
This took me so long to figure out. The damaged santa hat I was wearing caused my RAM to fill up and GC to take almost 10 seconds every few seconds.
